[project]
name = 'staking'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []

[repl]
clarity_wasm_mode = false
show_timings = false

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[contracts.trait-sip-010]
path = "contracts/traits/trait-sip-010.clar"
clarity_version = 2
epoch = 2.5

[contracts.trait-ownable]
path = "contracts/traits/trait-ownable.clar"
clarity_version = 2
epoch = 2.5

[contracts.trait-semi-fungible]
path = "contracts/traits/trait-semi-fungible.clar"
clarity_version = 2
epoch = 2.5

[contracts.sata-vault]
path = "contracts/sata-vault.clar"
depends_on = [
    "trait-sip-010",
    "trait-ownable",
    "trait-semi-fungible"
]
clarity_version = 2
epoch = 2.5

[contracts.stake]
path = 'contracts/stake.clar'
depends_on = [
    "trait-ownable",
    "trait-sip-010",
    "sata-vault"
]
clarity_version = 2
epoch = 2.5
